/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarouselComponent: typeof import('./src/components/HomeComponents/CarouselComponent.vue')['default']
    EventFilterComponent: typeof import('./src/components/EventComponents/EventFilterComponent.vue')['default']
    EventListComponent: typeof import('./src/components/EventComponents/EventListComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    IntroTextComponent: typeof import('./src/components/HomeComponents/IntroTextComponent.vue')['default']
    LoginComponent: typeof import('./src/components/Login-SignUpComponents/LoginComponent.vue')['default']
    LoginSignUpComponent: typeof import('./src/components/Login-SignUpComponents/Login-SignUpComponent.vue')['default']
    MenuComponent: typeof import('./src/components/MenuComponent.vue')['default']
    NewEventComponent: typeof import('./src/components/HomeComponents/NewEventComponents/NewEventComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpComponent: typeof import('./src/components/Login-SignUpComponents/SignUpComponent.vue')['default']
    SingleEventComponent: typeof import('./src/components/EventComponents/SingleEventComponent.vue')['default']
    SingleNewEventComponent: typeof import('./src/components/HomeComponents/NewEventComponents/SingleNewEventComponent.vue')['default']
  }
}
