/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/ErrorView': RouteRecordInfo<'/ErrorView', '/ErrorView', Record<never, never>, Record<never, never>>,
    '/MenusView/AllEventsView': RouteRecordInfo<'/MenusView/AllEventsView', '/MenusView/AllEventsView', Record<never, never>, Record<never, never>>,
    '/MenusView/HomeView': RouteRecordInfo<'/MenusView/HomeView', '/MenusView/HomeView', Record<never, never>, Record<never, never>>,
    '/MenusView/Login-ProfileView': RouteRecordInfo<'/MenusView/Login-ProfileView', '/MenusView/Login-ProfileView', Record<never, never>, Record<never, never>>,
    '/OtherView/EventPageView': RouteRecordInfo<'/OtherView/EventPageView', '/OtherView/EventPageView', Record<never, never>, Record<never, never>>,
    '/ProfilesView/GestionEventView': RouteRecordInfo<'/ProfilesView/GestionEventView', '/ProfilesView/GestionEventView', Record<never, never>, Record<never, never>>,
    '/ProfilesView/GestionProfileView': RouteRecordInfo<'/ProfilesView/GestionProfileView', '/ProfilesView/GestionProfileView', Record<never, never>, Record<never, never>>,
  }
}
