/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/MenuView/AllEventsView': RouteRecordInfo<'/MenuView/AllEventsView', '/MenuView/AllEventsView', Record<never, never>, Record<never, never>>,
    '/MenuView/HomeView': RouteRecordInfo<'/MenuView/HomeView', '/MenuView/HomeView', Record<never, never>, Record<never, never>>,
    '/MenuView/Login-ProfileView': RouteRecordInfo<'/MenuView/Login-ProfileView', '/MenuView/Login-ProfileView', Record<never, never>, Record<never, never>>,
    '/OtherView/EventOrganisatorView': RouteRecordInfo<'/OtherView/EventOrganisatorView', '/OtherView/EventOrganisatorView', Record<never, never>, Record<never, never>>,
    '/OtherView/EventView': RouteRecordInfo<'/OtherView/EventView', '/OtherView/EventView', Record<never, never>, Record<never, never>>,
    '/OtherView/GestionProfileView': RouteRecordInfo<'/OtherView/GestionProfileView', '/OtherView/GestionProfileView', Record<never, never>, Record<never, never>>,
  }
}
